### ISSUE TITLE
Help to integrate with reactive forms

### ISSUE THREAD

**Issue by shiva-p17** [judgewest2000/Ionic3RichText#2]
Hi 
Thanks for the nice component. I have an issue when I try to use with ionic 3  reactive form.

my form config as follow,
```
`export class MyPage implements OnInit {
thread: FormGroup;
ngOnInit() {
this.thread = new FormGroup({
            //thread_title: new FormControl('', [Validators.required, Validators.minLength(4)]),
            //formModel: new FormControl('', [Validators.required]),
            thread_content: new FormControl(this._content, [Validators.required]),
        });
}

```
`
In the HTML page 
 <rich-text [formControlItem]="thread_content" placeholderText="A sample of placeholder text"></rich-text> 

Am getting error as "property 'valid' of undefined"

Can you please help me on this. 

Thanks 
Shiva.P

**Comment by judgewest2000** [comment]
Hi Shiva,

Trust you're doing okay.

It should be a fairly easy fix.  On your `formControlItem` you just need to give it a little help finding the actual form control by telling it what the full path is: `thread.get('thread_content')`

thus...

`<rich-text [formControlItem]="thread.get('thread_content')" placeholderText="A sample of placeholder text">`

Let me know how you get on...

Thanks,

judgewest2000

**Comment by shiva-p17** [comment]
Thank you so much :)

How to validate without the attribute "**formControlName**"

Thanks
Shiva.P
