### ISSUE TITLE
Adding a new button to insert image

### ISSUE THREAD

**Issue by shiva-p17** [judgewest2000/Ionic3RichText#3]
Hi 

Is there any possible that I can add a button on my page (ionic-3) and update/ add image to the text area?

Thanks in advance.

Shiva.P

**Comment by judgewest2000** [comment]
Hi Shiva,

Quite possibly. What is your image source however? Base64 / public URL??

**Comment by shiva-p17** [comment]
Hi Brother,

 Thanks for the response and the image source will be base64 (mobile camera image).

Regards,
Shiva.P

**Comment by judgewest2000** [comment]
Hi Shiva,

For kicks I've created a branch where you can do exactly that.  I'm just mocking a base64 image so you'll need to do your own implementation, but you should get the idea...

https://github.com/judgewest2000/Ionic3RichText/tree/add-image

**Comment by shiva-p17** [comment]
Thank you judgewest2000
